name: build_deploy_reusable.yml
on:
  workflow_call:
    inputs:
      ANYPOINT_ENVIRONMENT:
        required: true
        type: string
      GITHUB_ENVIRONMENT:
        required: true
        type: string                    
      ANYPOINT_BUSINESSGROUP:
        required: true
        type: string  
      ANYPOINT_TARGET_NAME:
        required: true
        type: string 
      ANYPOINT_TARGET_TYPE:
        required: true
        type: string
    secrets:
      ANYPOINT_CLIENT_ID:
        required: true    
      ANYPOINT_CLIENT_SECRET:
        required: true
      ANYPOINT_CLIENT_ID_SECRET:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.GITHUB_ENVIRONMENT }}    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.ref}}        
        
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: 'maven'
        java-version: 8
        server-id: github

    - uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: '[{"id": "mule-connected-app", "username": "~~~Client~~~", "password": "${{ secrets.ANYPOINT_CLIENT_ID_SECRET }}"}]'

    - name: JOB settings DETAILS
      run: |
        cat /home/runner/.m2/settings.xml
        
    - name: Clean Test for development branch
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      run: mvn clean test               

    - name: Build and Test for development branch
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      run: mvn clean package      

    - name: Build and Test for release and production
      if: ${{ github.event.ref != 'refs/heads/develop' }}
      run: mvn clean package -DskipTests      

    - name: Publish MUnit Coverage Reports
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@v2
      with:
        name: munit-coverage-reports
        path: target/site/munit/coverage/*

    - name: Publish MUnit Test Reports
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@v2
      with:
        name: munit-test-reports
        path: target/surefire-reports/*

    # Add email these reports, zip - TBD
        
    - name: Configure Git user
      if: ${{ github.event.ref != 'refs/heads/develop' }}
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        
    - name: prepare release and perform
      continue-on-error: true
      if: ${{ github.event.ref != 'refs/heads/develop' }}
      run: mvn -B release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        
    - name: Deploy for ${{ github.event.ref }} branch
      run: |
        mvn -U -V -e -B -DskipTests deploy --file pom.xml -DmuleDeploy \
        -Dtarget_server_name=${{ inputs.ANYPOINT_TARGET_NAME}} \
        -Dtarget_type=${{ inputs.ANYPOINT_TARGET_TYPE}} \
        -Denvironment=${{ inputs.ANYPOINT_ENVIRONMENT}} \
        -Dbusinessgroup_id=${{ inputs.ANYPOINT_BUSINESSGROUP}} \
        -Dclient_id=${{ secrets.ANYPOINT_CLIENT_ID}} \
        -Dclient_secret=${{ secrets.ANYPOINT_CLIENT_SECRET}} \
