name: ci_cd_pipeline_develop.yml

# Run on a new push to develop branch
on:
  push:
    branches:
      - develop


jobs:
  develop:
    environment: Dev
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      ANYPOINT_ENVIRONMENT: ${{ vars.ANYPOINT_ENVIRONMENT }}
      GITHUB_ENVIRONMENT: "Dev"      
      ANYPOINT_BUSINESSGROUP: ${{ vars.ANYPOINT_BUSINESSGROUP }}
      ANYPOINT_TARGET_NAME: ${{ vars.ANYPOINT_TARGET_NAME }}
      ANYPOINT_TARGET_TYPE: ${{ vars.ANYPOINT_TARGET_TYPE }}
    secrets:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}       
      ANYPOINT_CLIENT_SECRET : ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_CLIENT_ID_SECRET: ${{ secrets.ANYPOINT_CLIENT_ID_SECRET }}
