name: ci_cd_pipeline_release_stage_prod.yml

# Run on new release creation or when manually triggered
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging or prod)?'     
        required: true
        default: 'staging'
env:
  ## Cloudhub Properties
  CLOUDHUB_WORKERS: 2
  CLOUDHUB_WORKER_TYPE: MICRO
  CLOUDHUB_REGION: us-east-01  

  ## API specific 
  HTTP_PRIVATE_PORT: 8091  

jobs:
  staging:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      ANYPOINT_ENVIRONMENT: "Stage"
      GITHUB_ENVIRONMENT: "Stage"      
      ANYPOINT_BUSINESSGROUP: "8d40a60d-8449-4188-94b7-c44d7e310394"
      ANYPOINT_TARGET_NAME: "MSI-MULESOFT-STG-CLUSTER"
      ANYPOINT_TARGET_TYPE: "cluster"
    secrets:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}       
      ANYPOINT_CLIENT_SECRET : ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_CLIENT_ID_SECRET: ${{ secrets.ANYPOINT_CLIENT_ID_SECRET }}

  prod:
    if: github.event.inputs.releaseType == 'prod'  
    needs: [staging]
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      ANYPOINT_ENVIRONMENT: "Prod"
      GITHUB_ENVIRONMENT: "Prod"      
      ANYPOINT_BUSINESSGROUP: "8d40a60d-8449-4188-94b7-c44d7e310394"
      ANYPOINT_TARGET_NAME: "MSI-MULESOFT-PROD-CLUSTER"
      ANYPOINT_TARGET_TYPE: "cluster"
    secrets:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}       
      ANYPOINT_CLIENT_SECRET : ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_CLIENT_ID_SECRET: ${{ secrets.ANYPOINT_CLIENT_ID_SECRET }}
