name: ci_cd_pipeline_develop.yml

# Run on a new push to develop branch
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging or prod)?'     
        required: true
        default: 'develop'


jobs:
  develop:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      ANYPOINT_ENVIRONMENT: "Dev"
      GITHUB_ENVIRONMENT: "Dev"      
      ANYPOINT_BUSINESSGROUP: "8d40a60d-8449-4188-94b7-c44d7e310394"
      ANYPOINT_TARGET_NAME: "MSI-MULESOFT-DEV"
      ANYPOINT_TARGET_TYPE: "server"
    secrets:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}       
      ANYPOINT_CLIENT_SECRET : ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_CLIENT_ID_SECRET: ${{ secrets.ANYPOINT_CLIENT_ID_SECRET }}
